joc/urls.py
    
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.views.generic import TemplateView
from django.conf.urls.static import static
from django.conf import settings
from account import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.homepage),  
    path('account/', include('account.urls')),  
    path('teacher/', include('teacher.urls')), 
    path('student/', include('student.urls')),   	
    path('captcha/', include('captcha.urls')),
    path('annotate/', include('annotate.urls')),
]

student/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from . import views
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('lessons/<int:subject_id>/', views.lessons),
    path('lesson/<int:lesson>/<int:unit>/', views.lesson),  
    path('classroom/', views.ClassroomList.as_view()),
    path('classroom/join/<int:kind>', views.ClassroomJoinList.as_view()),    
    path('classroom/<int:pk>/enroll/', views.ClassroomEnrollCreate.as_view()), 
    path('classroom/<int:pk>/classmate/', views.ClassmateList.as_view()),    
    path('classroom/<int:pk>/seat/', views.ClassroomSeatUpdate.as_view()),  
    path('classroom/<int:pk>/computer/', views.ClassroomComputerUpdate.as_view()),       
    #組別
    #path('group/<int:classroom_id>/', views.GroupPanel.as_view()),
    #path('group/join/<int:classroom_id>/<int:number>/<int:enroll_id>/', views.GroupJoin.as_view()),
    #組別
    path('group/<int:classroom_id>/', views.GroupListView.as_view()),
    path('group/list/<int:group_id>/', views.group_list),
    path('group/add/<int:group_id>/<int:number>/<int:enroll_id>/', views.group_join),	
    path('group/leader/<int:group_id>/<int:number>/<int:enroll_id>/', views.group_leader),	 	
    #查詢該作業分組小老師
    path('group/work/<int:typing>/<int:lesson>/<int:index>/<int:classroom_id>/', views.work_group),  	
    #公告
    path('announce/<int:classroom_id>/', views.AnnounceListView.as_view()),  	
    #作業上傳
    path('work/<int:typing>/<int:classroom_id>/', views.work),  
    path('work/download/<int:typing>/<int:lesson>/<int:index>/<int:user_id>/<int:workfile_id>/', views.work_download),  	
    path('work/groups/<int:classroom_id>/', views.work_groups),	
    path('work/show/<int:typing>/<int:lesson>/<int:index>/<int:user_id>/', views.show),
    path('work/submit/<int:typing>/<int:lesson>/<int:index>/', views.submit),	
    # 作業進度查詢
    path('progress/<int:typing>/<int:classroom_id>/<int:group_id>/', views.progress),  	
    #查詢該作業所有同學心得
    path('memo/<int:typing>/<int:classroom_id>/<int:index>/', views.memo),   
    path('memo/user/<int:typing>/<int:user_id>/<int:lesson>/<int:classroom_id>', views.memo_user),	
    #查詢某班級所有同學心得		
    path('memo/show/<int:typing><int:user_id>/<int:unit>/<int:classroom_id>/<int:score>/', views.memo_show),	
    path('memo/count/<int:typing>/<int:classroom_id>/<int:index>/', views.memo_count),        	
    path('memo/word/<int:typing>/<int:classroom_id>/<int:index>/<str:word>/', views.memo_word),
    #討論區
    path('forum/<int:classroom_id>/<int:bookmark>/', views.ForumList.as_view()),  
    path('forum/show/<int:index>/<int:user_id>/<int:classroom_id>/', views.ForumShow.as_view()),   
    path('forum/submit/<int:classroom_id>/<int:index>/', views.ForumSubmit.as_view()),    
	path('forum/publish/<int:classroom_id>/<int:index>/', views.ForumPublish.as_view()),
  	path('forum/publish/done/<int:classroom_id>/<int:index>/', views.ForumPublishDone.as_view()),
    path('forum/memo/<int:classroom_id>/<int:index>/<int:action>/', views.ForumMemo.as_view()),  
    #path('forum/file_delete/', login_required(views.forum_file_delete)), 	
    path('forum/history/<int:user_id>/<int:index>/<int:classroom_id>/', views.ForumHistory.as_view()),  
    path('forum/like/', views.forum_like),    
    path('forum/reply/', views.forum_reply),    	
    path('forum/people/', views.forum_people), 
    path('forum/guestbook/', views.forum_guestbook), 	
    path('forum/score/', views.forum_score),   
    path('forum/jieba/<int:classroom_id>/<int:index>/', views.ForumJieba.as_view()), 	
    path('forum/word/<int:classroom_id>/<int:index>/<str:word>/', views.ForumWord.as_view()),  
	path('forum/download/<int:file_id>/', views.forum_download), 
    path('forum/showpic/<int:file_id>/', views.forum_showpic), 		
	#問卷區
	#測驗
	path('exam/<int:classroom_id>/', login_required(views.ExamListView.as_view())), 
	path('exam/question/<int:classroom_id>/<int:exam_id>/<int:examwork_id>/<int:question_id>/', login_required(views.exam_question)), 	
	path('exam/answer/', login_required(views.exam_answer)), 	
	path('exam/submit/<int:classroom_id>/<int:exam_id>/<int:examwork_id>/', login_required(views.exam_submit)), 
	path('exam/score/<int:classroom_id>/<int:exam_id>/<int:examwork_id>/<int:user_id>/<int:question_id>/', login_required(views.exam_score)), 
    path('video/log/', views.video_log),
	#合作
	path('team/<int:classroom_id>/', login_required(views.TeamListView.as_view())), 
	path('team/stage/<int:classroom_id>/<int:grouping>/<int:team_id>/', login_required(views.team_stage)),                 
    path('team/content/<int:classroom_id>/<int:grouping>/<int:team_id>/<int:publish>/<int:stage>', login_required(views.TeamContentListView.as_view())), 
    path('team/content/add/<int:classroom_id>/<int:grouping>/<int:team_id>/', login_required(views.TeamContentCreateView.as_view())),
    path('team/content/delete/<int:classroom_id>/<int:grouping>/<int:team_id>/<int:content_id>/', login_required(views.team_delete)),   
    path('team/content/edit/<int:classroom_id>/<int:grouping>/<int:team_id>/<int:content_id>/', login_required(views.team_edit)),    
    path('team/publish/', login_required(views.team_make_publish)),             
    #測驗
    path('exam/', views.exam),
    path('exam_check/', views.exam_check),
    path('exam/score/', views.exam_score),    
]

student/models.py
# -*- coding: UTF-8 -*-
from django.db import models
from django.contrib.auth.models import User
from teacher.models import Classroom
from django.utils import timezone
from django.core.validators import RegexValidator, validate_comma_separated_integer_list

# 學生選課資料
class Enroll(models.Model):
    SCORE_CHOICES = [
        (100, "你好棒(100分)"),
        (90, "90分"),
        (80, "80分"),
        (70, "70分"),
        (60, "60分"),
        (40, "40分"),
        (20, "20分"),
        (0, "0分"),
    ]
    # 學生序號
    student_id = models.IntegerField(default=0)
    # 班級序號
    classroom_id = models.IntegerField(default=0)
    # 座號
    seat = models.IntegerField("座號", default=0)
    # 電腦
    computer = models.IntegerField("電腦", default=0)
    # 組別
    group = models.IntegerField("組別", default=-1)
    # 心得
    score_memo = models.IntegerField("指定作業心得成績", default=0, choices=SCORE_CHOICES)
    score_memo2 = models.IntegerField("自訂作業心得成績", default=0, choices=SCORE_CHOICES)
    # 註記
    score_annotations = models.IntegerField("註記成績", default=0, choices=SCORE_CHOICES)

    @property
    def classroom(self):
        return Classroom.objects.get(id=self.classroom_id)

    @property
    def student(self):
        return User.objects.get(id=self.student_id)

    def __str__(self):
        return str(self.id) + ":" + str(self.classroom_id) + ":" + str(self.student_id)

    def set_foo(self, x):
        self.groupshow = json.dumps(x)

    def get_groupshow(self):
        return json.loads(self.groupshow)

    class Meta:
        unique_together = ('classroom_id', 'student_id')


# 小老師
class WorkAssistant(models.Model):
    student_id = models.IntegerField(default=0)
    typing = models.IntegerField(default=0)
    group = models.IntegerField(default=0)
    index = models.IntegerField(default=0)
    lesson = models.IntegerField(default=0)
    classroom_id = models.IntegerField(default=0)

    @property
    def student(self):
        return User.objects.get(id=self.student_id)

class WorkGroup(models.Model):
    typing = models.IntegerField(default=0)
    classroom_id = models.IntegerField(default=0)
    index = models.IntegerField(default=0)
    group_id = models.IntegerField(default=0)

    class Meta:
        unique_together = ('classroom_id', 'index', 'typing')

def upload_path_handler(instance, filename):
    return "static/certificate/0/{filename}".format(filename=instance.id+".jpg")

class Work(models.Model):
    HELP_CHOICES = [
        (0, "全部靠自己想"),
        (1, "同學幫一點忙"),
        (2, "同學幫很多忙"),
        (3, "解答幫一點忙"),
        (4, "解答幫很多忙"),
        (5, "老師幫一點忙"),
        (6, "老師幫很多忙"),
    ]

    SCORE_OPTIONS = [
        (-2, ""),
        (100, "100分"),
        (90, "90分"),
        (80, "80分"),
        (70, "70分"),
        (60, "60分"),
        (-1, "重交"),
    ]

    user_id = models.IntegerField(default=0)
    lesson = models.IntegerField(default=0)
    typing = models.IntegerField(default=0)
    index = models.IntegerField()
    memo = models.TextField('心得感想')
    memo_c = models.IntegerField(default=0)
    memo_e = models.IntegerField(default=0)
    publish = models.BooleanField(default=False)
    publication_date = models.DateTimeField(default=timezone.now)
    score = models.IntegerField('成績', default=-2, choices=SCORE_OPTIONS)
    scorer = models.IntegerField('評分人id', default=0)
	# scratch, microbit
    file = models.FileField()
    #　python
    picture = models.ImageField('執行結果', upload_to = upload_path_handler, default = '/static/python/null.jpg')
    code = models.TextField('程式碼', default='')
    helps = models.IntegerField('創作過程', default=0, choices=HELP_CHOICES)
    answer = models.BooleanField(default=False)
    youtube = models.TextField(default='')
    comment = models.TextField('評語回饋', default='', blank=True, null=True)

    def __unicode__(self):
        user = User.objects.filter(id=self.user_id)[0]
        index = self.index
        return user.first_name+"("+str(index)+")"

    @property
    def user(self):
        return User.objects.get(id=self.user_id)


#解答
class Answer(models.Model):
    student_id = models.IntegerField(default=0)
    lesson_id = models.IntegerField(default=0)
    index = models.IntegerField()

    def __unicode__(self):
        user = User.objects.filter(id=self.student_id)[0]
        index = self.index
        return user.first_name+"("+str(index)+")"

class WorkFile(models.Model):
    work_id = models.IntegerField(default=0)
    filename = models.TextField()
    upload_date = models.DateTimeField(default=timezone.now)

#討論區作業
class SFWork(models.Model):
    student_id = models.IntegerField(default=0)
    index = models.IntegerField(default=0)
    memo = models.TextField(default='')
    memo_e =  models.IntegerField(default=0)
    memo_c = models.IntegerField(default=0)
    publish = models.BooleanField(default=False)
    publication_date = models.DateTimeField(default=timezone.now)
    reply_date = models.DateTimeField(default=timezone.now)
    score = models.IntegerField(default=0)
    scorer = models.IntegerField(default=0)
    comment = models.TextField(default='',null=True,blank=True)
    comment_publication_date = models.DateTimeField(default=timezone.now)
    likes = models.TextField(default='')
    like_count = models.IntegerField(default=0)
    reply = models.IntegerField(default=0)

    def __unicode__(self):
        user = User.objects.filter(id=self.student_id)[0]
        index = self.index
        return user.first_name+"("+str(index)+")"

class SFContent(models.Model):
    index =  models.IntegerField(default=0)
    student_id = models.IntegerField(default=0)
    work_id = models.IntegerField(default=0)
    title =  models.CharField(max_length=250,null=True,blank=True)
    filename = models.CharField(max_length=60,null=True,blank=True)
    publication_date = models.DateTimeField(default=timezone.now)
    delete_date = models.DateTimeField(default=timezone.now)
    visible = models.BooleanField(default=True)

#討論留言
class SFReply(models.Model):
    index = models.IntegerField(default=0)
    work_id =  models.IntegerField(default=0)
    user_id = models.IntegerField(default=0)
    memo =  models.TextField(default='')
    publication_date = models.DateTimeField(default=timezone.now)



class StudentGroup(models.Model):
    group_id = models.IntegerField(default=0)
    enroll_id = models.IntegerField(default=0)
    group = models.IntegerField(default=0)

    class Meta:
        unique_together = ('enroll_id', 'group_id',)

class StudentGroupLeader(models.Model):
    group_id = models.IntegerField(default=0)
    group = models.IntegerField(default=0)
    enroll_id = models.IntegerField(default=0)

    class Meta:
        unique_together = ('group_id', 'group')


#思辨文章
class SSpeculationWork(models.Model):
    student_id = models.IntegerField(default=0)
    index = models.IntegerField()
    memo = models.TextField(default='')
    publish = models.BooleanField(default=False)
    publication_date = models.DateTimeField(default=timezone.now)
    reply_date = models.DateTimeField(default=timezone.now)
    score = models.IntegerField(default=0)
    scorer = models.IntegerField(default=0)
    comment = models.TextField(default='',null=True,blank=True)
    comment_publication_date = models.DateTimeField(default=timezone.now)
    likes = models.TextField(default='')
    like_count = models.IntegerField(default=0)
    reply = models.IntegerField(default=0)

    def __unicode__(self):
        user = User.objects.filter(id=self.student_id)[0]
        index = self.index
        return user.first_name+"("+str(index)+")"

class SSpeculationContent(models.Model):
    index =  models.IntegerField(default=0)
    student_id = models.IntegerField(default=0)
    work_id = models.IntegerField(default=0)
    title =  models.CharField(max_length=250,null=True,blank=True)
    filename = models.CharField(max_length=60,null=True,blank=True)
    publication_date = models.DateTimeField(default=timezone.now)
    delete_date = models.DateTimeField(default=timezone.now)
    visible = models.BooleanField(default=True)


#測驗
class ExamWork(models.Model):
    student_id = models.IntegerField(default=0)
    exam_id = models.IntegerField()
    questions = models.TextField(default='')
    publish = models.BooleanField(default=False)
    publication_date = models.DateTimeField(default=timezone.now)
    score = models.IntegerField(default=0)
    scorer = models.IntegerField(default=0)

    def __unicode__(self):
        user = User.objects.filter(id=self.student_id)[0]
        exam_id = self.exam_id
        return user.first_name+"("+str(exam_id)+")"

#測驗答案
class ExamAnswer(models.Model):
    examwork_id = models.IntegerField(default=0)
    question_id = models.IntegerField(default=0)
    student_id = models.IntegerField(default=0)
    answer = models.TextField(default='')
    answer_right = models.BooleanField(default=False)

    class Meta:
        unique_together = ('student_id', 'examwork_id', 'question_id')

class TeamContent(models.Model):
    team_id =  models.IntegerField(default=0)
    user_id = models.IntegerField(default=0)
    types = models.IntegerField(default=0)
    title = models.CharField(max_length=250,null=True,blank=True)
    memo = models.TextField(default='')
    link = models.CharField(max_length=250,null=True,blank=True)
    youtube = models.CharField(max_length=250,null=True,blank=True)
    youtube_length = models.IntegerField(default=0)
    file = models.FileField(blank=True,null=True)
    filename = models.CharField(max_length=60,null=True,blank=True)
    publication_date = models.DateTimeField(default=timezone.now)
    publish = models.BooleanField(default=False)

class CourseContentProgress(models.Model):
    student_id = models.IntegerField(default=0)
    content_id = models.IntegerField(default=0)
    progress =models.IntegerField(default=0)
    start_time = models.DateTimeField(default=timezone.now)
    finish_time = models.DateTimeField(default=timezone.now)

    class Meta:

student/templates/student/announce_list.html
{% extends "base.html" %}
{% block content %}
        <h3>班級名稱：{{classroom.name}}</h3>
        <table class="table">
            <tr>
                <td>時間</td>
                <td>主旨</td>
        {% for message in messages %}
            <tr>
            <td>{{message.1.time}}</td>
            <td><a href="/account/message/{{message.0.id}}">{{message.1.title}}</a></td>
            </tr>
        {% endfor %}
        </table>
    {% load pagination %}
    {% get_pagination %}          
{% endblock %}

student/templates/student/classroom_join.html
{% extends "base.html" %}
{% load tag %}
{% block content %}
<a href="/student/classroom/join/0" class="btn btn-{% if not kind == 0 %}outline-{% endif %}info">全部課程</a>
<a href="/student/classroom/join/1" class="btn btn-{% if not kind == 1 %}outline-{% endif %}info">教師課程</a>
<table class="table">
  <tr>
  <th>班級名稱</th>   
  <th>開課教師</th>    
  <th>功能</th>       
  </tr>
{% for classroom, enrolled in queryset %}
  <tr>
  <td>{{classroom.name}}</td>
  <td>{{classroom.teacher_id|nickname}}</td>
  <td>
    {% if enrolled %}
    已加入
    {% else %}
    <a href="/student/classroom/{{classroom.id}}/enroll">加入班級</a>
    {% endif %}
  </td>
  </tr>
{% endfor %}
</table>
    {% load pagination %}
    {% get_pagination %}
{% endblock %}

student/templates/student/exam_list.html
{% extends "base.html" %}
{% load tag %}
{% block content %}
<button class="btn btn-success">{{classroom_id|classname}}</button>
					{% for exam, examwork, exmaclass, examworks, question_count, examclass, retest in exams %}
					{% if exam.opening %}
<h2 id="{{work.id}}"></h2>
<div class="card card-default">
	<div class="card-header">{{exam.title}} {% if not examwork %}<font color=red>(尚未交卷)</font>{% endif %} -- {{examclass.publication_date}} {{exam.user_id|nickname}}老師 -- 期限:{% if examclass.deadline %}{{examclass.deadline_date}}{% if examclass.deadline_date|alert and not examwork %}<font color=red>還剩 {{examclass.deadline_date|due}}</font><img src="/static/images/alert.png">{% endif %}{% else %}無{% endif %}</div>
  <div class="card-body">
		{% if not examclass.exam_id|in_deadline:classroom_id == '' or examwork or not question_count > 0 %}<button class="btn btn-default"><span class="glyphicon glyphicon-pencil" aria-hidden="true">作答({{examworks|length}})</span></button>{% else %}<a href="/student/exam/question/{{classroom_id}}/{{exam.id}}/{% if examworks|length == 0 %}0{% else %}{{examworks.0.id}}{% endif %}/0" class="btn btn-primary" role="btn"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> 作答({{examworks|length}})</a>{% endif %}
{% if examworks|length > 0 and examwork %}		
{% for examwork in examworks %}		
<a href="/student/exam/score/{{classroom_id}}/{{exam.id}}/{{examwork.id}}/{{request.user.id}}/0" class="btn btn-primary" role="btn"><span class="glyphicon glyphicon-zoom-in" aria-hidden="true"></span> 結果{{forloop.revcounter}}</a>	
{% endfor %}
{% if examwork and retest %}																								 
<a href="/student/exam/question/{{classroom_id}}/{{examclass.exam_id}}/{{examworks.0.id}}/0" class="btn btn-warning"><span class="glyphicon glyphicon-refresh" aria-hidden="true"></span>重考</a>
{% endif %}
{% endif %}
		{% if request.user.id == work.teacher_id %}	
<a href="/teacher/exam/{{classroom_id}}/#{{exam.id}}" class="btn btn-warning" role="btn"><span class="glyphicon glyphicon-flag" aria-hidden="true"></span> 教師</a>	
		{% endif %}
	</div>
</div>
        {% endif %}
        {% endfor %}
{% endblock %}

	{% block domready %}
	    $('body').css('background-image','url(/static/images/back1.gif)');
	{% endblock %}

student/templates/student/forum_jieba.html
{% extends "base.html" %}
{% load tz %}
{% block title %} Teachers {% endblock %}
{% block header %}
 <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
 <script type="text/javascript">
    google.charts.load("current", {packages:["corechart"]});
    google.charts.setOnLoadCallback(drawChart);
    function drawChart() {
      var data = google.visualization.arrayToDataTable([
        ["詞句", "出現次數"],
        {% for word in words %}
        ['{{word.0}} {{forloop.counter}}', {{word.1}}],
        {% endfor %}
      ]);
      var view = new google.visualization.DataView(data);
      view.setColumns([0,1]);
      var options = {
        title: "{{classroom.name}}心得用詞統計",
        width: 900,
        height: 300+{{words|length}}*40,
        chartArea:{top:60},       
      };
      var chart = new google.visualization.BarChart(document.getElementById("barchart_values"));
      chart.draw(view, options);
      var selectHandler = function(e) {
          window.location = "/student/forum/word/{{classroom.id}}/{{index}}/"+data.getValue(chart.getSelection()[0]['row'], 0 );
       }
       google.visualization.events.addListener(chart, 'select', selectHandler);
  }
  </script>
{% endblock %}
{% block content %}
<a href="/student/forum/{{classroom.id}}/{{index}}/" class="btn btn-success" role="btn">{{subject}}</a>
{% if words %}
<div id="barchart_values"></div>
{% else %}
尚未有心得發表
{% endif %}
{% endblock %}

student/templates/student/forum_word.html
{% extends "base.html" %}
{% load tag %}
{% block content %}
{{classroom.name}}的心得詞句：<font color=blue>{{word}}</font>
      {% for work, seat in datas %}
  <div class="card">
  <div class="card-header">
  {{seat}}){{work.student_id|realname}}
  </div>
  <div class="card-body">
   {{work.memo|memo|safe}}
  </div>
</div>

      {% endfor %}
    </table>
{% endblock %}

student/templates/student/memo.html
{% extends "base.html" %}
{% load tz %}
{% block title %} Teachers {% endblock %}
{% block content %}
        <table class="table">
        <tr>
            <td>座號</td>        
            <td>姓名</td>
            <td>心得</td>
        </tr>
        {% for data in datas %}
            <tr>
            <td>{{data.0.seat}}</td>
            <td nowrap><a href="/student/memo/user/{{typing}}/{{data.0.student_id}}/{{lesson}}/{{classroom_id}}">{{data.0.student.first_name}}</a></td>
            <td>{{data.1}}</td>            
            </tr>
        {% endfor %}
        </table>

{% endblock %}

student/templates/student/speculation_publish.html
{% extends "base.html" %}
{% load tag %}
{% block title %}Create a question{% endblock %}
{% block content %}
<a href="/student/speculation/publish/{{classroom_id}}/{{index}}/0" class="btn btn-default" role="btn">暫時不發表</a>   
<a href="/student/speculation/publish/{{classroom_id}}/{{index}}/1" class="btn btn-primary" role="btn">發表心得</a>           
{% endblock %}

student/templates/student/team_edit.html
{% extends "base.html" %}
{% load tag %}
{% block content %}
         <form action=""  method="post"  enctype="multipart/form-data">
           <input type=hidden name="forum_id" value="{{forum_id}}">
           <input type=hidden name="id" value="{{content.id}}">           
           <input type=hidden name="types" value="{{content.types}}">
           <ul class="list-group">
           {% if content.types == 1 %}
            <li class="list-group-item">
           文章褾題:<input id="id_title" maxlength="250" name="title" type="text" class="form-control list-group-item-text" placeholder="開啟連結" value="{% if content.title %}{{content.title}}{% endif %}">
           文章網址:<input id="id_link" maxlength="250" name="link" type="text" value="{{content.link}}" class="form-control list-group-item-text">
            </li>
        {% elif content.types == 2 %}
        <li class="list-group-item">        
            影片網址:<input id="id_content_youtube" maxlength="250" name="youtube" type="text" value={{content.youtube}} class="form-control list-group-item-text"/>
        </li>
      {% elif content.types == 3 %}
      <li class="list-group-item">
            檔案:<input id="id_content_file" name="content_file" type="file"/>
      </li>
        {% endif %}
    </ul>

 {% csrf_token %}
  <ul class="list-group">
    <li class="list-group-item">
      <h4 class="list-group-item-heading">說明</h4>
      <div class="list-group-item-text">
        <textarea name="memo" id="memo" cols="30" rows="10" class="form-control list-group-item-text">{{content.memo}}</textarea>
        <input class="button button-default" type="submit" value="送出">
      </div>      
    </li>
</ul>
<ul class="list-group">
    <li class="list-group-item material" id="m_{{ content.id }}">
      {% if content.types == 2 %}{% spaceless %}
        <button type="button" class="btn btn-primary btn-xs btn-add-marker">＋新增時間標記</button>
      {% endspaceless %}{% endif %}
      {% spaceless %}
        {% if content.types == 1 %}
        <a href="{{content.link}}" target="_blank">{% if content.title %}{{content.title}}{% else %}開啟連結{% endif %}</a>
        {% elif content.types == 2 %}
          <div class="embed-responsive embed-responsive-16by9">
        <iframe width="560" height="315" src="https://www.youtube.com/embed/{{content.youtube|number}}?enablejsapi=1" frameborder="0" allowfullscreen></iframe>
      </div>
            {% elif content.types == 3 %}
        <a href="/student/team/download/{{content.id}}" target="_blank">{{content.title}}</a> 
        {% endif %} 
      {% endspaceless %}
    </li>
  </ul> 
    </form>
{% endblock %}
{% block footer_script %}
<script>
function secToTime(sec) {
    return (new Date(sec*1000)).toUTCString().split(' ')[4];
}
function onYouTubeIframeAPIReady() {
  $('.material iframe[src*="www.youtube.com"]').each(function(index, element) {
      var materialID = $(element).parent().parent().attr('id');
      var playerID = materialID+'_player';
      var player;
      $(element).attr('id', playerID);
      player = new YT.Player(playerID);
      $(".btn-add-marker", $(element).parent().parent()).click(function(e) {
        var commentID = '#memo';
        var comment_body = $(commentID).val();
        if (comment_body)
          comment_body += "\n";
        comment_body += "["+materialID+"#"+secToTime(player.getCurrentTime().toFixed())+"]";
        $(commentID).val(comment_body).focus();
      });
  });
}
$(document).ready(function () {
  //------------------------------------------------------------------------
  // Load YouTube API library
  var tag = document.createElement('script');
  tag.id = 'iframe-demo';
  tag.src = 'https://www.youtube.com/iframe_api';
  var firstScriptTag = document.getElementsByTagName('script')[0];
  firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);  
});
</script>
{% endblock %}